--KONSTANTEN fuer Hunger und Lebenspunkte TODO: In Logic
HUNGER_IMPLEMENT = true
DIFFICULTY_VALUE = 0

HUNGER_PERIODIC_TICK = 900
HEALTH_PERIODIC_TICK = 300
HUNGER_DECREASE = 1.0
HEALTH_DECREASE = 50.0

HUNGER_DECREASE_DEPEND_CRAFT = 0.2
HUNGER_DECREASE_DEPEND_TILE = 0.1
HUNGER_DECREASE_DEPEND_ITEM = 0.2
HUNGER_DECREASE_DEPEND_BUILD = 0.2
HUNGER_DECREASE_DEPEND_REMOVE = 0.2

HEALTH_DECREASE_DEPEND_CRAFT = 4.0
HEALTH_DECREASE_DEPEND_TILE = 4.0
HEALTH_DECREASE_DEPEND_ITEM = 4.0
HEALTH_DECREASE_DEPEND_BUILD = 4.0

DEFAULT_ACQUIRE_RAW_FISH = 5

ADD_HUNGER_EATING_FISH = 20.0
ADD_HEALTH_EATING_FISH = 10.0