require ("prototypes.food_category")

require ("prototypes.items.salt_item")
require ("prototypes.items.gold_item")
require ("prototypes.items.goldbar_item")
require ("prototypes.items.goldwire_item")
require ("prototypes.items.sand_item")
require ("prototypes.items.glas_item")
require ("prototypes.items.humus_item")
require ("prototypes.items.kies_item")
require ("prototypes.items.nature_science_pack_item")
require ("prototypes.items.rice_item")
require ("prototypes.items.riceplant_item")
require ("prototypes.items.sojabean_item")
require ("prototypes.items.soja_item")
require ("prototypes.items.sojasouce_item")
require ("prototypes.items.garden_item")

require ("prototypes.recipes.salt_recipe")
require ("prototypes.recipes.gold_recipe")
require ("prototypes.recipes.goldbar_recipe")
require ("prototypes.recipes.goldwire_recipe")
require ("prototypes.recipes.kies_recipe")
require ("prototypes.recipes.glas_recipe")
require ("prototypes.recipes.sand_recipe")
require ("prototypes.recipes.humus_recipe")
require ("prototypes.recipes.nature_science_pack_recipe")

require ("prototypes.technologies.gold_technology")