HUNGER_IMPLEMENT = true

HUNGER_MAX_VALUE = 150

--DIFFICULTY LEVELS FOR HUNGER
DIFFICULTY_VALUE_EASY = 0
DIFFICULTY_VALUE_MEDIUM = 1
DIFFICULTY_VALUE_HARD = 2

--HUNGER_PERIODIC_TICK = 1000
HEALTH_PERIODIC_TICK = 300
HUNGER_DECREASE = 1.0
HEALTH_DECREASE = 50.0

HUNGER_DECREASE_DEPEND_CRAFT = 0.2
HUNGER_DECREASE_DEPEND_TILE = 0.1
HUNGER_DECREASE_DEPEND_ITEM = 0.2
HUNGER_DECREASE_DEPEND_BUILD = 0.05
HUNGER_DECREASE_DEPEND_REMOVE = 0.05

DEFAULT_ACQUIRE_RAW_FISH = 15

ADD_HUNGER_EATING_FISH = 10.0
ADD_HEALTH_EATING_FISH = 0.0

ADD_HUNGER_EATING_RAW_MEAT = 2.0
ADD_HEALTH_EATING_RAW_MEAT = -150.0

ADD_HUNGER_EATING_COOKED_MEAT = 20.0
ADD_HEALTH_EATING_COOKED_MEAT = 0.0

ADD_HUNGER_EATING_MUSHROOM = 2.0
ADD_HEALTH_EATING_MUSHROOM = 0.0

ADD_HUNGER_EATING_SUSHI = 25.0
ADD_HEALTH_EATING_SUSHI = 0.0

ADD_HUNGER_EATING_APPLE = 5.0
ADD_HEALTH_EATING_APPLE = 50.0

ADD_HUNGER_EATING_APPLEPIE = 30.0
ADD_HEALTH_EATING_APPLEPIE = 0.0

ADD_HUNGER_EATING_BREAD = 15.0
ADD_HEALTH_EATING_BREAD = 0.0

ADD_HUNGER_EATING_GOULASH = 30.0
ADD_HEALTH_EATING_GOULASH = 10.0

ADD_HUNGER_EATING_PIZZA = 25.0
ADD_HEALTH_EATING_PIZZA = 0.0

ADD_HUNGER_EATING_RICEPAN = 25.0
ADD_HEALTH_EATING_RICEPAN = 5.0

ADD_HUNGER_EATING_HAM = 15.0
ADD_HEALTH_EATING_HAM = 0.0

ADD_HUNGER_EATING_SCHNITZEL = 20.0
ADD_HEALTH_EATING_SCHNITZEL = 20.0

ADD_HUNGER_EATING_SOUP = 15.0
ADD_HEALTH_EATING_SOUP = 35.0

ADD_HUNGER_EATING_TOFU = 5.0
ADD_HEALTH_EATING_TOFU = 5.0

ADD_HUNGER_EATING_STEALTHSUSHI = 40.0
ADD_HEALTH_EATING_STEALTHSUSHI = 0.0