HUNGER_IMPLEMENT = true
DIFFICULTY_VALUE = 0

HUNGER_PERIODIC_TICK = 1000
HEALTH_PERIODIC_TICK = 300
HUNGER_DECREASE = 1.0
HEALTH_DECREASE = 50.0

HUNGER_DECREASE_DEPEND_CRAFT = 0.2
HUNGER_DECREASE_DEPEND_TILE = 0.1
HUNGER_DECREASE_DEPEND_ITEM = 0.2
HUNGER_DECREASE_DEPEND_BUILD = 0.2
HUNGER_DECREASE_DEPEND_REMOVE = 0.2

DEFAULT_ACQUIRE_RAW_FISH = 5

ADD_HUNGER_EATING_FISH = 10.0
ADD_HEALTH_EATING_FISH = 0.0

ADD_HUNGER_EATING_RAW_MEAT = 2.0
ADD_HEALTH_EATING_RAW_MEAT = -150.0

ADD_HUNGER_EATING_COOKED_MEAT = 15.0
ADD_HEALTH_EATING_COOKED_MEAT = 0.0

ADD_HUNGER_EATING_MUSHROOM = 2.0
ADD_HEALTH_EATING_MUSHROOM = 0.0

ADD_HUNGER_EATING_SUSHI = 15.0
ADD_HEALTH_EATING_SUSHI = 0.0

ADD_HUNGER_EATING_APPLE = 5.0
ADD_HEALTH_EATING_APPLE = 50.0

ADD_HUNGER_EATING_APPLEPIE = 15.0
ADD_HEALTH_EATING_APPLEPIE = 0.0

ADD_HUNGER_EATING_BREAD = 10.0
ADD_HEALTH_EATING_BREAD = 0.0

ADD_HUNGER_EATING_GOULASH = 20.0
ADD_HEALTH_EATING_GOULASH = 10.0

ADD_HUNGER_EATING_PIZZA = 20.0
ADD_HEALTH_EATING_PIZZA = 0.0

ADD_HUNGER_EATING_RICEPAN = 20.0
ADD_HEALTH_EATING_RICEPAN = 5.0

ADD_HUNGER_EATING_HAM = 10.0
ADD_HEALTH_EATING_HAM = 0.0

ADD_HUNGER_EATING_SCHNITZEL = 15.0
ADD_HEALTH_EATING_SCHNITZEL = 20.0

ADD_HUNGER_EATING_SOUP = 10.0
ADD_HEALTH_EATING_SOUP = 35.0

ADD_HUNGER_EATING_TOFU = 5.0
ADD_HEALTH_EATING_TOFU = 5.0

ADD_HUNGER_EATING_STEALTHSUSHI = 30.0
ADD_HEALTH_EATING_STEALTHSUSHI = 0.0